// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: live.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建直播课请求
type CreateLiveClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherName   string                 `protobuf:"bytes,1,opt,name=teacher_name,json=teacherName,proto3" json:"teacher_name,omitempty"` // 教师名称
	ClassName     string                 `protobuf:"bytes,2,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`       // 直播课名称
	RoomName      string                 `protobuf:"bytes,3,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLiveClassRequest) Reset() {
	*x = CreateLiveClassRequest{}
	mi := &file_live_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLiveClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLiveClassRequest) ProtoMessage() {}

func (x *CreateLiveClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLiveClassRequest.ProtoReflect.Descriptor instead.
func (*CreateLiveClassRequest) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLiveClassRequest) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

func (x *CreateLiveClassRequest) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *CreateLiveClassRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

// 创建直播课响应
type CreateLiveClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassId       string                 `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"` // 直播课ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                  // 状态信息
	StreamKey     string                 `protobuf:"bytes,3,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLiveClassResponse) Reset() {
	*x = CreateLiveClassResponse{}
	mi := &file_live_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLiveClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLiveClassResponse) ProtoMessage() {}

func (x *CreateLiveClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLiveClassResponse.ProtoReflect.Descriptor instead.
func (*CreateLiveClassResponse) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLiveClassResponse) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *CreateLiveClassResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateLiveClassResponse) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

// 加入直播课请求
type JoinLiveClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassId       string                 `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`             // 直播课ID
	StudentName   string                 `protobuf:"bytes,2,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"` // 学生名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLiveClassRequest) Reset() {
	*x = JoinLiveClassRequest{}
	mi := &file_live_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLiveClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLiveClassRequest) ProtoMessage() {}

func (x *JoinLiveClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLiveClassRequest.ProtoReflect.Descriptor instead.
func (*JoinLiveClassRequest) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{2}
}

func (x *JoinLiveClassRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *JoinLiveClassRequest) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

// 获取消息请求
type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassId       string                 `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`                    // 直播课ID
	LastTimestamp int64                  `protobuf:"varint,2,opt,name=last_timestamp,json=lastTimestamp,proto3" json:"last_timestamp,omitempty"` // 最后收到消息的时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_live_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{3}
}

func (x *GetMessagesRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *GetMessagesRequest) GetLastTimestamp() int64 {
	if x != nil {
		return x.LastTimestamp
	}
	return 0
}

// 获取消息响应
type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"` // 消息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_live_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{4}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

// 加入直播课响应
type JoinLiveClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                        // 状态信息
	StreamUrl     string                 `protobuf:"bytes,2,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"` // 播放地址
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                      // 附加消息（改为普通字符串）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinLiveClassResponse) Reset() {
	*x = JoinLiveClassResponse{}
	mi := &file_live_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinLiveClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinLiveClassResponse) ProtoMessage() {}

func (x *JoinLiveClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinLiveClassResponse.ProtoReflect.Descriptor instead.
func (*JoinLiveClassResponse) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{5}
}

func (x *JoinLiveClassResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JoinLiveClassResponse) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

func (x *JoinLiveClassResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 发送消息请求
type SendMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClassId        string                 `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`                      // 直播课ID
	SenderName     string                 `protobuf:"bytes,2,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`             // 发送者名称
	MessageContent string                 `protobuf:"bytes,3,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"` // 消息内容
	Message        *Message               `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_live_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{6}
}

func (x *SendMessageRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *SendMessageRequest) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *SendMessageRequest) GetMessageContent() string {
	if x != nil {
		return x.MessageContent
	}
	return ""
}

func (x *SendMessageRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// 发送消息响应
type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_live_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{7}
}

func (x *SendMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 消息类型
type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderName     string                 `protobuf:"bytes,1,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`             // 发送者名称
	MessageContent string                 `protobuf:"bytes,2,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"` // 消息内容
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                // 时间戳
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_live_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{8}
}

func (x *Message) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *Message) GetMessageContent() string {
	if x != nil {
		return x.MessageContent
	}
	return ""
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 结束直播课请求
type EndLiveClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassId       string                 `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"` // 直播课ID
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`              // 用户名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndLiveClassRequest) Reset() {
	*x = EndLiveClassRequest{}
	mi := &file_live_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndLiveClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndLiveClassRequest) ProtoMessage() {}

func (x *EndLiveClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndLiveClassRequest.ProtoReflect.Descriptor instead.
func (*EndLiveClassRequest) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{9}
}

func (x *EndLiveClassRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *EndLiveClassRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// 结束直播课响应
type EndLiveClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndLiveClassResponse) Reset() {
	*x = EndLiveClassResponse{}
	mi := &file_live_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndLiveClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndLiveClassResponse) ProtoMessage() {}

func (x *EndLiveClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndLiveClassResponse.ProtoReflect.Descriptor instead.
func (*EndLiveClassResponse) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{10}
}

func (x *EndLiveClassResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 发布题目请求
type PublishQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassId       string                 `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"` // 直播课ID
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`              // 题目内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishQuestionRequest) Reset() {
	*x = PublishQuestionRequest{}
	mi := &file_live_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishQuestionRequest) ProtoMessage() {}

func (x *PublishQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishQuestionRequest.ProtoReflect.Descriptor instead.
func (*PublishQuestionRequest) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{11}
}

func (x *PublishQuestionRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *PublishQuestionRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

// 发布题目响应
type PublishQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                           // 状态信息
	QuestionId    string                 `protobuf:"bytes,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"` // 题目ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishQuestionResponse) Reset() {
	*x = PublishQuestionResponse{}
	mi := &file_live_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishQuestionResponse) ProtoMessage() {}

func (x *PublishQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishQuestionResponse.ProtoReflect.Descriptor instead.
func (*PublishQuestionResponse) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{12}
}

func (x *PublishQuestionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PublishQuestionResponse) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

// 提交答案请求
type SubmitAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassId       string                 `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`             // 直播课ID
	StudentName   string                 `protobuf:"bytes,2,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"` // 学生名称
	Answer        string                 `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`                              // 答案内容
	QuestionId    string                 `protobuf:"bytes,4,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`    // 题目ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnswerRequest) Reset() {
	*x = SubmitAnswerRequest{}
	mi := &file_live_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerRequest) ProtoMessage() {}

func (x *SubmitAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerRequest.ProtoReflect.Descriptor instead.
func (*SubmitAnswerRequest) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{13}
}

func (x *SubmitAnswerRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *SubmitAnswerRequest) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *SubmitAnswerRequest) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *SubmitAnswerRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

// 提交答案响应
type SubmitAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAnswerResponse) Reset() {
	*x = SubmitAnswerResponse{}
	mi := &file_live_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAnswerResponse) ProtoMessage() {}

func (x *SubmitAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAnswerResponse.ProtoReflect.Descriptor instead.
func (*SubmitAnswerResponse) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{14}
}

func (x *SubmitAnswerResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 获取答题结果统计请求
type GetAnswerStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassId       string                 `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`          // 直播课ID
	QuestionId    string                 `protobuf:"bytes,2,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"` // 题目ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnswerStatisticsRequest) Reset() {
	*x = GetAnswerStatisticsRequest{}
	mi := &file_live_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnswerStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnswerStatisticsRequest) ProtoMessage() {}

func (x *GetAnswerStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnswerStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetAnswerStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{15}
}

func (x *GetAnswerStatisticsRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *GetAnswerStatisticsRequest) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

// 答题结果统计
type AnswerStatistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`                                                                                  // 题目ID
	AnswerCounts  map[string]int32       `protobuf:"bytes,2,rep,name=answer_counts,json=answerCounts,proto3" json:"answer_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 答案统计
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerStatistics) Reset() {
	*x = AnswerStatistics{}
	mi := &file_live_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerStatistics) ProtoMessage() {}

func (x *AnswerStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerStatistics.ProtoReflect.Descriptor instead.
func (*AnswerStatistics) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{16}
}

func (x *AnswerStatistics) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *AnswerStatistics) GetAnswerCounts() map[string]int32 {
	if x != nil {
		return x.AnswerCounts
	}
	return nil
}

// 题目类型
type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`       // 题目ID
	QuestionText  string                 `protobuf:"bytes,2,opt,name=question_text,json=questionText,proto3" json:"question_text,omitempty"` // 题目内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_live_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_live_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_live_proto_rawDescGZIP(), []int{17}
}

func (x *Question) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *Question) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

var File_live_proto protoreflect.FileDescriptor

const file_live_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"live.proto\x12\x05proto\"w\n" +
	"\x16CreateLiveClassRequest\x12!\n" +
	"\fteacher_name\x18\x01 \x01(\tR\vteacherName\x12\x1d\n" +
	"\n" +
	"class_name\x18\x02 \x01(\tR\tclassName\x12\x1b\n" +
	"\troom_name\x18\x03 \x01(\tR\broomName\"k\n" +
	"\x17CreateLiveClassResponse\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\tR\aclassId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x03 \x01(\tR\tstreamKey\"T\n" +
	"\x14JoinLiveClassRequest\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\tR\aclassId\x12!\n" +
	"\fstudent_name\x18\x02 \x01(\tR\vstudentName\"V\n" +
	"\x12GetMessagesRequest\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\tR\aclassId\x12%\n" +
	"\x0elast_timestamp\x18\x02 \x01(\x03R\rlastTimestamp\"A\n" +
	"\x13GetMessagesResponse\x12*\n" +
	"\bmessages\x18\x01 \x03(\v2\x0e.proto.MessageR\bmessages\"h\n" +
	"\x15JoinLiveClassResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x02 \x01(\tR\tstreamUrl\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xa3\x01\n" +
	"\x12SendMessageRequest\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\tR\aclassId\x12\x1f\n" +
	"\vsender_name\x18\x02 \x01(\tR\n" +
	"senderName\x12'\n" +
	"\x0fmessage_content\x18\x03 \x01(\tR\x0emessageContent\x12(\n" +
	"\amessage\x18\x04 \x01(\v2\x0e.proto.MessageR\amessage\"-\n" +
	"\x13SendMessageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"q\n" +
	"\aMessage\x12\x1f\n" +
	"\vsender_name\x18\x01 \x01(\tR\n" +
	"senderName\x12'\n" +
	"\x0fmessage_content\x18\x02 \x01(\tR\x0emessageContent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"L\n" +
	"\x13EndLiveClassRequest\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\tR\aclassId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\".\n" +
	"\x14EndLiveClassResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"O\n" +
	"\x16PublishQuestionRequest\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\tR\aclassId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\"R\n" +
	"\x17PublishQuestionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\tR\n" +
	"questionId\"\x8c\x01\n" +
	"\x13SubmitAnswerRequest\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\tR\aclassId\x12!\n" +
	"\fstudent_name\x18\x02 \x01(\tR\vstudentName\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\tR\x06answer\x12\x1f\n" +
	"\vquestion_id\x18\x04 \x01(\tR\n" +
	"questionId\".\n" +
	"\x14SubmitAnswerResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"X\n" +
	"\x1aGetAnswerStatisticsRequest\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\tR\aclassId\x12\x1f\n" +
	"\vquestion_id\x18\x02 \x01(\tR\n" +
	"questionId\"\xc4\x01\n" +
	"\x10AnswerStatistics\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12N\n" +
	"\ranswer_counts\x18\x02 \x03(\v2).proto.AnswerStatistics.AnswerCountsEntryR\fanswerCounts\x1a?\n" +
	"\x11AnswerCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"P\n" +
	"\bQuestion\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12#\n" +
	"\rquestion_text\x18\x02 \x01(\tR\fquestionText2\xf7\x04\n" +
	"\x10LiveClassService\x12P\n" +
	"\x0fCreateLiveClass\x12\x1d.proto.CreateLiveClassRequest\x1a\x1e.proto.CreateLiveClassResponse\x12L\n" +
	"\rJoinLiveClass\x12\x1b.proto.JoinLiveClassRequest\x1a\x1c.proto.JoinLiveClassResponse\"\x00\x12D\n" +
	"\vSendMessage\x12\x19.proto.SendMessageRequest\x1a\x1a.proto.SendMessageResponse\x12G\n" +
	"\fEndLiveClass\x12\x1a.proto.EndLiveClassRequest\x1a\x1b.proto.EndLiveClassResponse\x12P\n" +
	"\x0fPublishQuestion\x12\x1d.proto.PublishQuestionRequest\x1a\x1e.proto.PublishQuestionResponse\x12G\n" +
	"\fSubmitAnswer\x12\x1a.proto.SubmitAnswerRequest\x1a\x1b.proto.SubmitAnswerResponse\x12D\n" +
	"\vGetMessages\x12\x19.proto.GetMessagesRequest\x1a\x1a.proto.GetMessagesResponse\x12S\n" +
	"\x13GetAnswerStatistics\x12!.proto.GetAnswerStatisticsRequest\x1a\x17.proto.AnswerStatistics0\x01B\tZ\a.;protob\x06proto3"

var (
	file_live_proto_rawDescOnce sync.Once
	file_live_proto_rawDescData []byte
)

func file_live_proto_rawDescGZIP() []byte {
	file_live_proto_rawDescOnce.Do(func() {
		file_live_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_live_proto_rawDesc), len(file_live_proto_rawDesc)))
	})
	return file_live_proto_rawDescData
}

var file_live_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_live_proto_goTypes = []any{
	(*CreateLiveClassRequest)(nil),     // 0: proto.CreateLiveClassRequest
	(*CreateLiveClassResponse)(nil),    // 1: proto.CreateLiveClassResponse
	(*JoinLiveClassRequest)(nil),       // 2: proto.JoinLiveClassRequest
	(*GetMessagesRequest)(nil),         // 3: proto.GetMessagesRequest
	(*GetMessagesResponse)(nil),        // 4: proto.GetMessagesResponse
	(*JoinLiveClassResponse)(nil),      // 5: proto.JoinLiveClassResponse
	(*SendMessageRequest)(nil),         // 6: proto.SendMessageRequest
	(*SendMessageResponse)(nil),        // 7: proto.SendMessageResponse
	(*Message)(nil),                    // 8: proto.Message
	(*EndLiveClassRequest)(nil),        // 9: proto.EndLiveClassRequest
	(*EndLiveClassResponse)(nil),       // 10: proto.EndLiveClassResponse
	(*PublishQuestionRequest)(nil),     // 11: proto.PublishQuestionRequest
	(*PublishQuestionResponse)(nil),    // 12: proto.PublishQuestionResponse
	(*SubmitAnswerRequest)(nil),        // 13: proto.SubmitAnswerRequest
	(*SubmitAnswerResponse)(nil),       // 14: proto.SubmitAnswerResponse
	(*GetAnswerStatisticsRequest)(nil), // 15: proto.GetAnswerStatisticsRequest
	(*AnswerStatistics)(nil),           // 16: proto.AnswerStatistics
	(*Question)(nil),                   // 17: proto.Question
	nil,                                // 18: proto.AnswerStatistics.AnswerCountsEntry
}
var file_live_proto_depIdxs = []int32{
	8,  // 0: proto.GetMessagesResponse.messages:type_name -> proto.Message
	8,  // 1: proto.SendMessageRequest.message:type_name -> proto.Message
	18, // 2: proto.AnswerStatistics.answer_counts:type_name -> proto.AnswerStatistics.AnswerCountsEntry
	0,  // 3: proto.LiveClassService.CreateLiveClass:input_type -> proto.CreateLiveClassRequest
	2,  // 4: proto.LiveClassService.JoinLiveClass:input_type -> proto.JoinLiveClassRequest
	6,  // 5: proto.LiveClassService.SendMessage:input_type -> proto.SendMessageRequest
	9,  // 6: proto.LiveClassService.EndLiveClass:input_type -> proto.EndLiveClassRequest
	11, // 7: proto.LiveClassService.PublishQuestion:input_type -> proto.PublishQuestionRequest
	13, // 8: proto.LiveClassService.SubmitAnswer:input_type -> proto.SubmitAnswerRequest
	3,  // 9: proto.LiveClassService.GetMessages:input_type -> proto.GetMessagesRequest
	15, // 10: proto.LiveClassService.GetAnswerStatistics:input_type -> proto.GetAnswerStatisticsRequest
	1,  // 11: proto.LiveClassService.CreateLiveClass:output_type -> proto.CreateLiveClassResponse
	5,  // 12: proto.LiveClassService.JoinLiveClass:output_type -> proto.JoinLiveClassResponse
	7,  // 13: proto.LiveClassService.SendMessage:output_type -> proto.SendMessageResponse
	10, // 14: proto.LiveClassService.EndLiveClass:output_type -> proto.EndLiveClassResponse
	12, // 15: proto.LiveClassService.PublishQuestion:output_type -> proto.PublishQuestionResponse
	14, // 16: proto.LiveClassService.SubmitAnswer:output_type -> proto.SubmitAnswerResponse
	4,  // 17: proto.LiveClassService.GetMessages:output_type -> proto.GetMessagesResponse
	16, // 18: proto.LiveClassService.GetAnswerStatistics:output_type -> proto.AnswerStatistics
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_live_proto_init() }
func file_live_proto_init() {
	if File_live_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_live_proto_rawDesc), len(file_live_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_live_proto_goTypes,
		DependencyIndexes: file_live_proto_depIdxs,
		MessageInfos:      file_live_proto_msgTypes,
	}.Build()
	File_live_proto = out.File
	file_live_proto_goTypes = nil
	file_live_proto_depIdxs = nil
}
